### ISSUE TITLE
Broken by mathcomp change 

### ISSUE THREAD

**Issue by SkySkimmer** [imdea-software/fcsl-pcm#17]
https://github.com/math-comp/math-comp/commit/d60c67b8f33f55e11ca159246d2a447102f10f20 "Change the order of arguments in `ltngtP`"
used https://github.com/imdea-software/fcsl-pcm/blob/e565b808d26ee63f296f672721c6e68de27ec677/pcm/natmap.v#L296 (and perhaps elsewhere)

Note that this breaks Coq's CI

**Comment by anton-trunov** [comment]
Should be fixed now

**Comment by anton-trunov** [comment]
Ok, looks like the fix works. Closing this issue for now. Feel free to reopen.
