### ISSUE TITLE
Coq 8.12 compatibility in opam

### ISSUE THREAD

**Issue by palmskog** [imdea-software/fcsl-pcm#22]
Any chance for marking some opam package (either the one in `extra-dev`, or the one for 1.2.0, or even the repo one) as compatible with Coq 8.12? Currently, there is no way for me to test in CI that Disel works with 8.12 via opam, despite that it works fine locally with 8.12+beta1.

**Comment by anton-trunov** [comment]
Done for this repo and here a pending PR: https://github.com/coq/opam-coq-archive/pull/1309

**Comment by palmskog** [comment]
Thanks, Disel CI works fine now.
