### ISSUE TITLE
Official Coq 8.8.0 and mathcomp 1.7 support in OPAM

### ISSUE THREAD

**Issue by palmskog** [imdea-software/fcsl-pcm#3]
According to my quick evaluation, `fcsl-pcm` works fine with the recently released Coq 8.8.0 and mathcomp 1.7. Any chance to get this reflected in the OPAM package in the Coq OPAM repository? No new release should be required, just new dependencies along the lines of
```
"coq" {>= "8.7" & < "8.9~"}
"coq-mathcomp-ssreflect" {>= "1.6.2" & < "1.8~"}
```
would be sufficient.

**Comment by anton-trunov** [comment]
See here: https://github.com/coq/opam-coq-archive/pull/312

**Comment by palmskog** [comment]
Thanks!
