### ISSUE TITLE
MathComp 2.0 support

### ISSUE THREAD

**Issue by palmskog** [imdea-software/fcsl-pcm#41]
Are there any plans for to support MathComp 2.0? It would be nice to port Disel to MathComp 2.0, but then I need both FCSL PCM and HTT to have releases compatible with [2.0.0](https://github.com/math-comp/math-comp/releases/tag/mathcomp-2.0.0) or later. See [porting guide](https://github.com/math-comp/math-comp/blob/master/etc/porting_to_mathcomp2/porting.pdf).

**Comment by aleksnanevski** [comment]
I would clearly have to do that at some point. However, it sounds like it will be a very serious undertaking.

**Comment by aleksnanevski** [comment]
Yes, we have already done the work, but it will take us a few days to build a release package.
