### ISSUE TITLE
Name collision for path_last

### ISSUE THREAD

**Issue by palmskog** [imdea-software/fcsl-pcm#5]
Both `finmap/ordtype.v` and `pcm/heap.v` have a lemma called `path_last`, with different meanings. This causes the importing order of files to matter, and proofs to break when the importing order is changed. Any chance the lemma in `pcm/heap.v` could get a different name?

**Comment by anton-trunov** [comment]
Thanks for reporting this! I should be able to fix it the next week.

**Comment by anton-trunov** [comment]
@palmskog Hi Karl, I hope this fixes the issue, so I'm closing it for now. Feel free to reopen if something goes wrong for you.
