### ISSUE TITLE
Broken with math-comp master

### ISSUE THREAD

**Issue by ejgallego** [imdea-software/fcsl-pcm#7]
Hi folks,

as per @ggonthier detailed analysis [here](https://github.com/math-comp/math-comp/pull/294#issuecomment-478772950), current fcsl-pcm is broken in math-comp master which in turn makes it broken in Coq's CI.

Could you please apply the suggested fix?

Thanks!

**Comment by anton-trunov** [comment]
Hi @ejgallego! Thanks for opening the issue. I incorporated the fix by @ggonthier (thank you) in  f65fa08de125cf5b76de66f439ef977b4edb6061.

**Comment by ejgallego** [comment]
Thanks @anton-trunov for the quick response!
